- name: ENSURE THE ROUTER ELEMENTS EXIST FOR SITE1
  include_role:
    name: provision_site1
    tasks_from: provision_elements.yaml

- name: ENSURE THE ROUTER ELEMENTS EXIST FOR SITE2
  include_role:
    name: provision_site2
    tasks_from: provision_elements.yaml
