---
- name: ENSURE THAT THE DEV SITE IS ADDED TO TOWER
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    tower_instance: "https://54.144.88.64/"
    project_name: ajay-netdevops
    org_name: devops

  tasks:
    - name: ENSURE THAT ROUTER CREDENTIALS ARE IN TOWER
      tower_credential:
        tower_host: "{{ tower_instance }}"
        tower_password: "{{ tower_pass }}"
        tower_username: "{{ tower_user }}"
        name: "{{ ec2_name_prefix }}"
        organization: "{{ org_name }}"
        kind: ssh
        ssh_key_data: "./{{ ec2_name_prefix }}/{{ ec2_name_prefix }}.pem"
        project: "{{ project_name }}"
        tower_verify_ssl: no
