- name: ADD ROUTERS TO SITE2 GROUP
  add_host:
    name: "{{ item.tags.Name }}"
    #short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: ec2-user
    ansible_port: 22
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    private_ip: "{{item.private_ip_address}}"
    ansible_network_os: ios
    groups:
      - site2
      - dev
      - full
  with_items:
    - "{{ core2_facts.instances }}"
    - "{{ remote2_facts.instances }}"
