- name: GRAB FACTS FOR CORE1 NODE
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:device": "core"
      "tag:location": "site1"
      "tag:project": "{{ ec2_name_prefix }}"
  register: core1_facts

- name: GRAB FACTS FOR REMOTE1 NODE
  ec2_instance_facts:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:device": "remote1"
      "tag:location": "site1"
      "tag:project": "{{ ec2_name_prefix }}"
  register: remote1_facts


- name: BUILD HOSTVARS
  template:
    src: generate_vars.j2
    dest: "{{ playbook_dir }}/group_vars/site1/plumbing.yaml"
  #when: "'site1' or 'site2' in env"
